# Generated by Django 3.0 on 2020-01-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200115_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
