# Generated by Django 3.0.3 on 2020-02-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200115_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='This user has not added any bio information.', max_length=500, null=True),
        ),
    ]
