# Generated by Django 3.0.2 on 2020-01-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200117_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='tags',
        ),
    ]
