# Generated by Django 3.0.3 on 2020-02-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200213_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='text',
            new_name='main_text',
        ),
        migrations.RemoveField(
            model_name='page',
            name='description',
        ),
        migrations.AddField(
            model_name='page',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
