# Generated by Django 3.0.3 on 2020-02-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200220_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='main_text',
            field=models.TextField(blank=True),
        ),
    ]
